import { gzipSync } from "node:zlib";
import { readFileSync, writeFileSync } from "node:fs";

const sourceUrl = new URL(
    "../firmware/CardputerAssistant/assets/web_console.html",
    import.meta.url,
);
const outputUrl = new URL(
    "../firmware/CardputerAssistant/src/web_console_asset.h",
    import.meta.url,
);

const source = Buffer.from(
    readFileSync(sourceUrl, "utf8").replace(/\r\n/g, "\n"),
    "utf8",
);
const compressed = gzipSync(source, { level: 9, mtime: 0 });
const rows = [];
for (let offset = 0; offset < compressed.length; offset += 16) {
    const values = [...compressed.subarray(offset, offset + 16)]
        .map((value) => `0x${value.toString(16).padStart(2, "0")}`);
    rows.push(`    ${values.join(", ")},`);
}

const header = `#pragma once

#include <Arduino.h>

#include <cstddef>
#include <cstdint>

namespace cardputer {

// Generated by tools/embed_web_console.mjs. Do not edit manually.
inline constexpr std::uint8_t kWebConsolePageGzip[] PROGMEM = {
${rows.join("\n")}
};
inline constexpr std::size_t kWebConsolePageGzipSize = sizeof(kWebConsolePageGzip);

}  // namespace cardputer
`;

writeFileSync(outputUrl, header, "utf8");
console.log(
    `WEB_CONSOLE_ASSET source=${source.length} gzip=${compressed.length}`,
);
